export default {
  userLogin: '/api/user/login',
  adminLogin:'/admin/login',
  userList:'/admin/user/all/list',
  financialList:'/admin/financial/organs/all/list',
  governmentList:'/admin/government/department/all/list',
  financialDelete:'/admin/financial/organs/delete',
  financialDetail:'/admin/financial/organs/detail',
  financialSave:'/admin/financial/organs/save',
  getArea:'/get/area',
  policyList:'/admin/enterprise/service/policy/all/list',
  policyThemeFeature:'/admin/policy/theme/feature/list',
  policyDetail:'/enterprise/service/policy/detail',
  policySave:'/admin/enterprise/service/policy/save',
  policyDelete:'/admin/enterprise/service/policy/delete',
  permission:'/admin/get/permission',
  financialOrgs:'/admin/financial/organs/all/list',

  guaranteeList:'/admin/guarantee/all/list',
  guaranteeSave:'/admin/guarantee/save',
  guaranteeDetail:'/admin/guarantee/detail',

  fundList:'/admin/fund/all/list',
  fundDetail:'/admin/fund/detail',
  fundSave:'/admin/fund/save',
  fundDelete:'/admin/fund/delete',

  insuranceList:'/admin/insurance/all/list',
  insuranceDetail:'/admin/insurance/detail',
  insuranceSave:'/admin/insurance/save',
  insuranceDelete:'/admin/insurance/delete',

  loanList:'/admin/bank/loan/all/list',
  loanDetail:'/admin/bank/loan/detail',
  loanSave:'/admin/bank/loan/save',
  loanDelete:'/admin/bank/loan/delete',

  allList:'/all/list',
  userInfo:'/user/info',
  applyList:'/apply/all/list',
  departmentList:'/admin/government/department/all/list',
  adminUserLogout:'/admin/user/logout',
};
