export default {
  userLogin: '/api/user/login',
  adminLogin:'/admin/login',
  userList:'/admin/user/all/list',
  financialList:'/admin/financial/organs/all/list',
  governmentList:'/admin/government/department/all/list',
  financialDelete:'/admin/financial/organs/delete',
  financialDetail:'/admin/financial/organs/detail',
  financialSave:'/admin/financial/organs/save',
  getArea:'/get/area',
  policyList:'/admin/enterprise/service/policy/all/list',
  policyThemeFeature:'/admin/policy/theme/feature/list',
  policyDetail:'/enterprise/service/policy/detail',
  policySave:'/admin/enterprise/service/policy/save',
  policyDelete:'/admin/enterprise/service/policy/delete',
  permission:'/admin/get/permission',
  financialOrgs:'/admin/financial/organs/all/list',

  guaranteeList:'/admin/guarantee/all/list',
  guaranteeSave:'/admin/guarantee/save',
  guaranteeDetail:'/admin/guarantee/detail',

  fundList:'/admin/fund/all/list',
  fundDetail:'/admin/fund/detail',
  fundSave:'/admin/fund/save',
  fundDelete:'/admin/fund/delete',

  insuranceList:'/admin/insurance/all/list',
  insuranceDetail:'/admin/insurance/detail',
  insuranceSave:'/admin/insurance/save',
  insuranceDelete:'/admin/insurance/delete',

  loanList:'/admin/bank/loan/all/list',
  loanDetail:'/admin/bank/loan/detail',
  loanSave:'/admin/bank/loan/save',
  loanDelete:'/admin/bank/loan/delete',

  allList:'/all/list',
  userInfo:'/user/info',
  applyList:'/apply/all/list',
  departmentList:'/admin/government/department/all/list',
  adminUserLogout:'/admin/user/logout',
  applyAction:'/apply/info/action',
  adminUpdateInfo:'/admin/user/updateInfo',

  financialUserList:'/admin/financial/organs/user/all/list',
  financialUserDetail:'/admin/financial/organs/user/detail',
  financialUserDelete:'/admin/financial/organs/user/delete',

  governmentUserList:'/admin/government/department/user/all/list',
  governmentDepartmentSave:'/admin/government/department/save',
  governmentDepartmentDetail:'/admin/government/department/detail',
  governmentUserSave:'/admin/government/department/user/save',
  governmentUserDetail:'/admin/government/department/user/detail',
  governmentDepartmentDelete:'/admin/government/department/delete',
  governmentDepartmentUserDelete:'/admin/government/department/user/delete',
  adminPermission:'/admin/save/permission',
  organsUserSave:'/admin/financial/organs/user/save'
};
